//! Type aliases for convenience
//! 
//! Note: This module provides additional aliases but may have naming conflicts
//! with the generated aliases from individual quantity modules. Consider using
//! explicit imports to resolve conflicts.

// Placeholder - aliases will be generated by macros in individual quantity modules